// Code generated by MockGen. DO NOT EDIT.
// Source: internal/content/writer/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/content/writer/interface.go -destination=internal/content/writer/interface_mock.go -package=writer
//

// Package writer is a generated GoMock package.
package writer

import (
	context "context"
	"github.com/IsaacDSC/search_content/internal/content/entity"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, enterpriseKey entity.EnterpriseKey) (EnterpriseData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, enterpriseKey)
	ret0, _ := ret[0].(EnterpriseData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, enterpriseKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, enterpriseKey)
}

// Save mocks base method.
func (m *MockRepository) Save(ctx context.Context, enterprise entity.Enterprise) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, enterprise)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(ctx, enterprise any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), ctx, enterprise)
}
